name: linux_style_check
on: [push, pull_request]
jobs:
  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    # Allowing non-const references as discussed in ISO C++ guidelines here
    # https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-inout
    # This is not allowed in Google's C++ style guide.
    - run: cpplint --filter=-build/include_subdir,-runtime/reference --recursive .
